name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # her 12 saatte bir çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: eabaci42
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      - uses: Platane/snk@master
        id: snake-gif-dark
        with:
          github_user_name: eabaci42
          svg_out_path: dist/github-contribution-grid-snake-dark.svg
          snake_color: 'blue'
          color_snake: "#0891b2"
          color_dots: "#24292e,#1e6823,#38a256,#44eb88"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 